# Generated by Django 3.2 on 2022-02-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency_unit',
            table='currency_unit',
        ),
    ]
