# Generated by Django 3.2 on 2022-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
