# Generated by Django 3.2 on 2022-02-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_currency_unit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='list_item',
            old_name='list_id',
            new_name='list',
        ),
    ]
