# Generated by Django 3.2 on 2022-05-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='meal_plan',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
