# Generated by Django 3.2 on 2022-05-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220515_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='list_item',
            old_name='list',
            new_name='list_id',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='menu',
            new_name='menu_id',
        ),
    ]
