# Generated by Django 3.2 on 2022-05-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220518_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_type',
            new_name='meal_type_id',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='menu_item',
            old_name='measurement_unit',
            new_name='measurement_unit_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='currency_unit',
            new_name='currency_unit_id',
        ),
    ]
