# Generated by Django 3.2 on 2022-05-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220518_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.item'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.menu'),
        ),
    ]
