# Generated by Django 3.2 on 2022-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_menu_item_item_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name', 'user_id'), name='unique_item_per_user'),
        ),
    ]
